export const types = {
    //Sync
    FETCH_SERVICES_REQUEST: 'FETCH_SERVICES_REQUEST',
    FETCH_SERVICES_FAILED: 'FETCH_SERVICES_FAILED',
    FETCH_SERVICES_SUCCESS: 'FETCH_SERVICES_SUCCESS',

    //Async
    FETCH_SERVICES_ASYNC: 'FETCH_SERVICES_ASYNC',
}