export const tendersTypes = {
  // Sync
  RESET_TENDERS_TABLE: 'tenders/RESET_TENDERS_TABLE',
  FETCH_SERVICES_REQUEST: 'tenders/FETCH_SERVICES_REQUEST',
  FETCH_SERVICES_SUCCESS: 'tenders/FETCH_SERVICES_SUCCESS',
  FETCH_SERVICES_FAILURE: 'tenders/FETCH_SERVICES_FAILURE',

  FETCH_TENDERS_REQUEST: 'tenders/FETCH_TENDERS_REQUEST',
  FETCH_TENDERS_SUCCESS: 'tenders/FETCH_TENDERS_SUCCESS',
  FETCH_TENDERS_FAILURE: 'tenders/FETCH_TENDERS_FAILURE',

  FETCH_TENDER_STATUS_HISTORY_REQUEST:
    'tenders/FETCH_TENDER_STATUS_HISTORY_REQUEST',
  FETCH_TENDER_STATUS_HISTORY_SUCCESS:
    'tenders/FETCH_TENDER_STATUS_HISTORY_SUCCESS',
  FETCH_TENDER_STATUS_HISTORY_FAILURE:
    'tenders/FETCH_TENDER_STATUS_HISTORY_FAILURE',

  FETCH_TENDER_EDIT_LOG_REQUEST:
    'tenders/FETCH_TENDER_EDIT_LOG_REQUEST',
  FETCH_TENDER_EDIT_LOG_SUCCESS:
    'tenders/FETCH_TENDER_EDIT_LOG_SUCCESS',
  FETCH_TENDER_EDIT_LOG_FAILURE:
    'tenders/FETCH_TENDER_EDIT_LOG_FAILURE',

  UPDATE_ONE_TENDER: 'tenders/UPDATE_ONE_TENDER',

  // Async
  FETCH_SERVICES_ASYNC: 'tenders/FETCH_SERVICES_ASYNC',
  FETCH_TENDERS_ASYNC: 'tenders/FETCH_TENDERS_ASYNC',
  CREATE_TENDER_ASYNC: 'tenders/CREATE_TENDER_ASYNC',
  DELETE_TENDER_ASYNC: 'tenders/DELETE_TENDER_ASYNC',
  EDIT_TENDER_ASYNC: 'tenders/EDIT_TENDER_ASYNC',
  SIGN_TENDER_ASYNC: 'tenders/SIGN_TENDER_ASYNC',
  EDIT_TENDER_STATUS_ASYNC: 'tenders/EDIT_TENDER_STATUS_ASYNC',
  ADD_TENDER_ITEMS_ASYNC: 'tenders/ADD_TENDER_ITEMS_ASYNC',
  FETCH_TENDER_STATUS_HISTORY_ASYNC:
    'tenders/FETCH_TENDER_STATUS_HISTORY_ASYNC',
  FETCH_TENDER_EDIT_LOG_ASYNC: 'tenders/FETCH_TENDER_EDIT_LOG_ASYNC',
  CONFIRM_OR_REJECT_ASYNC: 'tenders/CONFIRM_OR_REJECT_ASYNC',
  COMPLETE_FROM_DISPATCHER: 'tenders/COMPLETE_FROM_DISPATCHER',
};
