export const types = {
    //Sync
    FETCH_FLIGHT_REQUEST: 'FETCH_FLIGHT_REQUEST',
    FETCH_FLIGHT_FAILED: 'FETCH_FLIGHT_FAILED',
    FETCH_FLIGHT_SUCCESS: 'FETCH_FLIGHT_SUCCESS',

    //Async
    FETCH_FLIGHT_ASYNC: 'FETCH_FLIGHT_ASYNC',
}