export const types = {
    //Sync
    FETCH_EXECUTORS_REQUEST: 'FETCH_EXECUTORS_REQUEST',
    FETCH_EXECUTORS_FAILED: 'FETCH_EXECUTORS_FAILED',
    FETCH_EXECUTORS_SUCCESS: 'FETCH_EXECUTORS_SUCCESS',

    //Async
    FETCH_EXECUTORS_ASYNC: 'FETCH_EXECUTORS_ASYNC',
    ADD_FLIGHT_EXECUTOR_ASYNC: 'ADD_FLIGHT_EXECUTOR',
    ADD_FLIGHT_TKO_ASYNC: 'ADD_FLIGHT_EXECUTOR',
}