export const attachmentsTypes = {
  // Sync
  FETCH_ATTACHMENT_REQUEST: 'attachments/FETCH_ATTACHMENT_REQUEST',
  FETCH_ATTACHMENT_SUCCESS: 'attachments/FETCH_ATTACHMENT_SUCCESS',
  FETCH_ATTACHMENT_FAILURE: 'attachments/FETCH_ATTACHMENT_FAILURE',

  // Async
  FETCH_ATTACHMENT_ASYNC: 'tenders/FETCH_ATTACHMENT_ASYNC',
};
