export const types = {
    //Sync
    FETCH_TASKS_REQUEST: 'FETCH_TASKS_REQUEST',
    FETCH_TASKS_FAILED: 'FETCH_TASKS_FAILED',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',

    //Async
    FETCH_TASKS_ASYNC: 'FETCH_TASKS_ASYNC',
}