export const usersTypes = {
    // Sync
    FETCH_USERS_REQUEST: 'users/FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'users/FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'users/FETCH_USERS_FAILURE',
    DELETE_USER: 'users/DELETE_USER',
    UPDATE_USER_SUCCESS: 'users/UPDATE_USER_SUCCESS',

    // Async
    FETCH_USERS_ASYNC: 'users/FETCH_USERS_ASYNC',
    DELETE_USER_ASYNC: 'users/DELETE_USER_ASYNC',
    ARCHIVE_USER_ASYNC: 'users/ARCHIVE_USER_ASYNC',
    BLOCK_USER_ASYNC: 'users/BLOCK_USER_ASYNC',
    ADD_USER_ASYNC: 'users/ADD_USER_ASYNC',
    ADD_DRAFT_USER_ASYNC: 'users/ADD_DRAFT_USER_ASYNC',
    UPDATE_USER_ASYNC: 'users/UPDATE_USER_ASYNC',
    FETCH_ADRESS_BOOK_ASYNC: 'users/FETCH_ADRESS_BOOK_ASYNC',
    FETCH_DOC_ADRESS_BOOK_ASYNC: 'users/FETCH_DOC_ADRESS_BOOK_ASYNC',
};
