export const types = {
  //Sync
  RESET_FLIGHTS: 'RESET_FLIGHTS',
  FETCH_FLIGHTS_REQUEST: 'FETCH_FLIGHTS_REQUEST',
  FETCH_FLIGHTS_FAILED: 'FETCH_FLIGHTS_FAILED',
  FETCH_FLIGHTS_SUCCESS: 'FETCH_FLIGHTS_SUCCESS',

  //Async
  FETCH_FLIGHTS_ASYNC: 'FETCH_FLIGHTS_ASYNC',
};
