export const types = {
    //Sync
    FETCH_REPORTS_REQUEST: 'FETCH_REPORTS_REQUEST',
    FETCH_REPORTS_FAILED: 'FETCH_REPORTS_FAILED',
    FETCH_REPORTS_SUCCESS: 'FETCH_REPORTS_SUCCESS',

    //Async
    FETCH_REPORTS_ASYNC: 'FETCH_REPORTS_ASYNC',
}